name: Semgrep SAST

on:
  push:
    branches: [main]  
  pull_request: {}
  workflow_dispatch: {}   
permissions:
  contents: read
  security-events: write  
jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    container:        
      image: semgrep/semgrep:1.119.0

    steps:
      - uses: actions/checkout@v4  

      - name: Run Semgrep with custom rules
        run: |
          semgrep scan --config .semgrep \
                       --sarif --output semgrep.sarif

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3 
        with:
          sarif_file: semgrep.sarif
        if: always()

